---
- name: "[VULN] mssql_sa_weak_password — Set weak SA password"
  ansible.windows.win_shell: |
    sqlcmd -S localhost -U SA -P "Coco2024!" -Q "ALTER LOGIN SA WITH PASSWORD='sa123';"
  when: "'dc-mssql' in vm_role"
  ignore_errors: true
